### PR TITLE
Python 3.11 requirements

### LINKED ISSUE #363: Installation on Python 3.11 fails
During `pip3 install requirements.txt`, the build fails when Python 3.11 is used, even when `python3-dev` is installed.

```
#0 27.66       copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-cpython-311/cytoolz/tests
#0 27.66       running build_ext
#0 27.66       building 'cytoolz.dicttoolz' extension
#0 27.66       creating build/temp.linux-x86_64-cpython-311
#0 27.66       creating build/temp.linux-x86_64-cpython-311/cytoolz
#0 27.66       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-cpython-311/cytoolz/dicttoolz.o
#0 27.66       cytoolz/dicttoolz.c:211:12: fatal error: longintrepr.h: No such file or directory
#0 27.66         211 |   #include "longintrepr.h"
#0 27.66             |            ^~~~~~~~~~~~~~~
#0 27.66       compilation terminated.
#0 27.66       error: command '/usr/bin/gcc' failed with exit code 1
#0 27.66       [end of output]
#0 27.66   
#0 27.66   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 27.66   ERROR: Failed building wheel for cytoolz
#0 27.67   Running setup.py clean for cytoolz
```

### PR DESCRIPTION
**Pull request by yorickdowne**
Updating cytoolz and toolz allows staking-deposit-cli to build with Python 3.11 / 3.12.

The hashes in this PR cover cytoolz on all architectures from Python 3.8 through Python 3.12. They were fetched with the helper script in https://github.com/ethereum/staking-deposit-cli/pull/377 , with a minimum Python version of 3.8.

CI for Python 3.11 and 3.12 has been added, which required typed-ast to be removed from `requirements_test.txt`. As typed-ast is obsolete from Python 3.8, that should be fine.

Closes #363

### CODE REVIEW

**Comment by yorickdowne** [comment]
Note that because `requirements.txt` now includes hashes, this will need to be updated with fresh cytoolz hashes each Python release: 3.12 in October 2023, then 3.13 a year after, &c.

**Comment by yorickdowne** [comment]
This helps it build with Python 3.11, but it then doesn't function: Need to fix a mutable default first. Hang loose.

**Comment by yorickdowne** [comment]
`keystore.py` had a small zoo of these:
```
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'staking_deposit.key_handling.keystore.KeystoreModule'> for field kdf is not allowed: use default_factory
```

I've changed all instances to use a default_factory.

This is due to this change in 3.11:

```
* Change field default mutability check, allowing only defaults which are
  :term:`hashable` instead of any object which is not an instance of
  :class:`dict`, :class:`list` or :class:`set`. (Contributed by Eric V. Smith in
  :issue:`44674`.)
```

**Comment by yorickdowne** [comment]
The requirements.txt hashes were fetched with the helper script in #377 , with a minimum Python version of 3.8

**Comment by eth2353** [comment]
I ran into this error (and similar ones) on Python 3.11 too:

`ValueError: mutable default <class 'staking_deposit.key_handling.keystore.KeystoreModule'> for field kdf is not allowed: use default_factory`

I fixed it in my own fork before looking if there was a PR addressing it. Anyway, I came up with pretty much the same solution, except I used a lambda instead of the partial object and it seems to preserve more readability to me, see [here](https://github.com/eth2353/staking-deposit-cli/commit/45c52514e4b2a8c254db92216a728b7c5776a4f5) . So just adding my 2 cents, consider using the lambda?

Also, an unnecessary extra `@dataclass` decorator seems to have sneaked in at line 63 🙂

**Comment by yorickdowne** [comment]
Your solution is way more elegant @eth2353 ! Thank you, adopted.

**Comment by yorickdowne** [comment]
@holiman Can I pull you in for review? This changes requirements.txt and some of the code so it works with Python 3.11.

**Comment by holiman** [comment]
Me??

Better leave this for @CarlBeek

**Comment by yorickdowne** [comment]
I tried a tox-py312, but that changes so many dependencies and then causes mypy errors, that I backed that out. staking-deposit-cli does appear to work (mostly?) on 3.12 with these 3.11 changes, but CI for it fails. Let's do 3.12 in a separate PR.

tox-py311 works, but required typed-ast to be removed. As typed-ast is obsolete from Python 3.8, I don't see an issue.
